/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-104013-g2ee4077248-20211005"
#endif /* AVUTIL_FFVERSION_H */
